name: Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Find gradlew
        run: |
          echo "Ищем gradlew..."
          find . -name "gradlew"

      - name: Build APK
        run: |
          set -e
          DIR=$(find . -type f -name "gradlew" | head -n 1 | xargs dirname)
          echo "Найден проект в: $DIR"
          chmod +x "$DIR/gradlew"
          cd "$DIR"
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: app-debug
          path: "**/*.apk"
          if-no-files-found: error
