name: Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Find project folder
        run: |
          echo "Ищем gradlew..."
          find . -name "gradlew"

      - name: Build APK
        run: |
          for dir in $(find . -type f -name "gradlew"); do
            folder=$(dirname "$dir")
            echo "Собираем в $folder"
            chmod +x "$folder/gradlew"
            cd "$folder"
            ./gradlew assembleDebug --no-daemon
            cd -
            break
          done

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: app-debug
          path: "**/*.apk"
          if-no-files-found: error
